### ISSUE TITLE
rojo plugin install fails (rc.1)

### ISSUE THREAD

**Issue by jeparlefrancais** [Roblox/rojo#339] opened 2020-07-08 13:42 UTC
After installing version `6.0.0-rc.1` and running `rojo plugin install`, it produces the following error:

`[ERROR] Rojo requires a project file, but no project file was found in path plugin`

It seems like the project file is not correctly bundled with the binary.

**Comment by LPGhatguy** [comment] 2020-07-08 18:45
Duplicate of #320, closed in da05078.

**Closed by LPGhatguy** 2020-07-08 18:45 UTC
